name: Test and Publish

on:
  - push
  - pull_request

jobs:
  is-duplicate:
    name: Is Duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    permissions:
      actions: write
      contents: read

    steps:
      - id: skip-check
        name: Skip Check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**/README.md"]'

  test-code:
    name: Test code
    runs-on: ${{ matrix.os }}
    needs: is-duplicate
    if: ${{ needs.is-duplicate.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests] tox-gh-actions
          pip install .[examples]

      - name: Test with Tox
        run: tox

  publish-to-test-pypi:
    name: Publish to TestPyPI
    environment: staging
    runs-on: ubuntu-20.04
    needs:
      - is-duplicate
      - test-code
    if: |
      needs.is-duplicate.outputs.should_skip != 'true' &&
      github.ref == 'refs/heads/master' &&
      github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*

  publish-to-pypi:
    name: Publish to PyPI
    environment: production
    runs-on: ubuntu-20.04
    needs:
      - is-duplicate
      - publish-to-test-pypi
    if: |
      needs.is-duplicate.outputs.should_skip != 'true' &&
      github.ref == 'refs/heads/master' &&
      github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
